### ISSUE TITLE
Support for osx-arm64 / noarch

### ISSUE THREAD

**Issue by YanJinad** [thatch/moreorless#7]
Would it be possible to get a noarch or osx-arm64 build configuration for this package for conda-forge ?

**Comment by thatch** [comment]
I think https://github.com/conda-forge/moreorless-feedstock would be a better place to file your request.  The configuration in this repo already works this way:

```
$ python setup.py bdist_wheel
...
creating moreorless-0.4.0-py2.py3-none-any.whl
```

**Comment by YanJinad** [comment]
Thanks @thatch
